# ===============================
# DATASET BUILD CONFIG
# ===============================

dataset:
  videos_dir: "C:/GP/Dataset/NTU_RGB_Action43"
  out_root: "C:/GP/Dataset/NTU_RGB_Action43_Processed"
  fps: 5
  val_ratio: 0.2
  seed: 42

detector:
  weights: "model_weights/patient_detection_yolov8n.pt"
  imgsz: 960
  conf: 0.35
  iou: 0.45
  max_det: 15

filtering:
  min_box_area: 1024  # 32*32

# ===============================
# QUICK TEST CONFIG
# ===============================

test:
  video: "C:/GP/Video Project 2.mp4"
  out_video: "runtime_outputs/patient_detection_yolo_quick_test.mp4"
  conf: 0.25
  iou: 0.45
  imgsz: 960
  max_det: 15
